name: cartpole
args: []
kwargs: {}

dataset:
  _target_: "datasets.cartpole_dset.load_cartpole_slice_train_val"
  n_rollout: null
  normalize_action: ${normalize_action}
  data_path: ${oc.env:DATASET_DIR}/cartpole
  data_file: episodes.pth
  episode_len: 500
  split_ratio: 0.9
  action_scale: 1.0
  transform:
    _target_: "datasets.img_transforms.default_transform"
    img_size: ${img_size}

decoder_path: null
num_workers: 8
